name: Quick Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python3 test_yaml_fuse.py --unit
    
    - name: Run demo
      run: |
        python3 test_yaml_fuse.py --demo
    
    - name: Check syntax
      run: |
        python3 -c "import yaml; print('✅ PyYAML import successful')"
        python3 -m py_compile yaml-fuse.py
        python3 -m py_compile test_yaml_fuse.py
        python3 -m py_compile functional_tests.py
        echo "✅ All Python files compile successfully"
    
    - name: Check documentation
      run: |
        test -f README.md && echo "✅ README.md exists"
        test -f TESTING.md && echo "✅ TESTING.md exists"
        test -f LICENSE && echo "✅ LICENSE exists"
        test -f requirements.txt && echo "✅ requirements.txt exists"
        echo "✅ All documentation files present" 